US-1889327: Header fixes
dotnet/docs-desktop pull request #1319
Opened 2022-02-24 07:34 UTC by poojapoojari

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2022-02-25 11:26 UTC, poojapoojari commented
Hello @adegeo!

The 6th PR with 20 file edits is ready for technical review. Could you please review this PR?
Thank you!

2022-02-25 17:50 UTC, adegeo requested changes
Thanks! some minor things to change.

2022-02-25 17:50 UTC, adegeo commented on dotnet-desktop-guide/framework/wpf/controls/how-to-create-apply-template.md
> +| `Template Intro Sample` | `WidthAndHeight` | `250` |
This is better the other way around. You can use Property / Value for the headers
```suggestion
| Property          | Value                   |
| ----------------- | ----------------------- |
| **Title**         | `Template Intro Sample` |
| **SizeToContent** | `WidthAndHeight`        |
| **MinWidth**      | `250`                   |
```

2022-02-25 17:50 UTC, adegeo commented on dotnet-desktop-guide/framework/wpf/controls/how-to-create-apply-template.md
> +| `roundbutton` | `Button` |
Property/Value as headers here too

2022-02-25 17:50 UTC, adegeo commented on dotnet-desktop-guide/framework/wpf/controls/how-to-retrieve-a-text-selection.md
> +## C# example on OnClick event handler
This also has VB.NET code so no reason to point out C# here
```suggestion
## OnClick event handler
```

2022-02-28 12:21 UTC, poojapoojari commented
Hello @adegeo,

Thank you for your feedback! I have updated the content for the same. Could you please have a look and approve the changes?

Thank you!

2022-02-28 16:53 UTC, adegeo approved these changes
Looks good, thanks!

2022-02-28 16:53 UTC, merged