Content update - Property changed events (user story 1878475)
dotnet/docs-desktop pull request #1350
Opened 2022-04-07 20:10 UTC by v-trisshores

2022-04-08 18:15 UTC, adegeo requested changes
Awesome. Few minor changes to implement, otherwise ready to go!

2022-04-08 18:15 UTC, adegeo commented on dotnet-desktop-guide/net/wpf/events/property-change-events.md
> +Property trigger syntax is analogous to an "if" statement in programming. If the trigger condition is true, then the "body" of the property trigger is "executed". The "body" of a property trigger isn
Terminology suggests that we use "run" over "execute" if we can.
```suggestion
Property trigger syntax is analogous to an "if" statement in programming. If the trigger condition is true, then the "body" of the property trigger is "run". The "body" of a property trigger isn't code, its markup. That markup is limited to using one or more <xref:System.Windows.Setter> elements to set other properties of the object where the style or template is applied.
```

2022-04-08 18:37 UTC, v-trisshores commented
@adegeo, thanks for your review! The suggested changes are committed.

2022-04-13 15:47 UTC, adegeo approved these changes

2022-04-13 15:47 UTC, adegeo commented
Awesome, thanks!!

2022-04-13 15:48 UTC, merged